import type { TraceabilityRow } from '@ave/core-domain/types'

export const TRACEABILITY_ROWS: TraceabilityRow[] = [
  {
    businessObjective: 'BUS-001 Demonstrate the decision chain',
    operationalRequirement: 'Every recommendation is safety-validated before display',
    systemRequirement: 'SAFE-101–104',
    useCase: 'UC-03 Detect and respond to main engine degradation',
    hazardOrConstraint: 'HAZ-ME-01 Unplanned main engine derating',
    component: 'safety-engine/validate.ts, decision-engine/builders.ts',
    testScenario: 'ENGINE DEGRADATION',
    verificationEvidence: 'Unit test: packages/safety-engine/src/validate.test.ts · Unit test: packages/simulator/src/simulation/engine.scenarios.test.ts (full sense-to-audit chain)',
    verificationStatus: 'verified',
  },
  {
    businessObjective: 'BUS-002 Reduce workload, preserve authority',
    operationalRequirement: 'Related alarms correlate into one probable operational condition',
    systemRequirement: 'HMI-101',
    useCase: 'UC-06 Correlate an alarm cascade',
    hazardOrConstraint: 'HAZ-OPS-02 Alarm flooding masking the underlying cause',
    component: 'decision-engine/alarmCorrelation.ts',
    testScenario: 'ALARM CASCADE',
    verificationEvidence: 'Unit test: packages/decision-engine/src/alarmCorrelation.test.ts',
    verificationStatus: 'verified',
  },
  {
    businessObjective: 'BUS-002 Reduce workload, preserve authority',
    operationalRequirement: 'Navigation authority remains with the bridge team',
    systemRequirement: 'NAV-001–003',
    useCase: 'UC-04 Evaluate a developing collision risk',
    hazardOrConstraint: 'HAZ-NAV-01 Loss of situational awareness under closing risk',
    component: 'simulation/navigation.ts, features/operations/*',
    testScenario: 'COLLISION-RISK DEVELOPMENT',
    verificationEvidence: 'Unit test: packages/core-domain/src/utils/geo.test.ts (CPA/TCPA geometry) · e2e: packages/app/e2e/acceptance-journey.spec.ts ("CPA develops progressively without any autonomous course change")',
    verificationStatus: 'verified',
  },
  {
    businessObjective: 'BUS-002 Reduce workload, preserve authority',
    operationalRequirement: 'Reefer excursions are detected and escalated with cargo exposure',
    systemRequirement: 'CARGO-001–002',
    useCase: 'UC-05 Manage a reefer temperature excursion',
    hazardOrConstraint: 'HAZ-CGO-01 Temperature-sensitive cargo loss',
    component: 'simulation/engine.ts (reefer branch), features/cargo/*',
    testScenario: 'REEFER TEMPERATURE EXCURSION',
    verificationEvidence: 'Unit test: packages/simulator/src/simulation/engine.scenarios.test.ts ("REEFER TEMPERATURE EXCURSION scenario") · No e2e coverage yet',
    verificationStatus: 'partial',
  },
  {
    businessObjective: 'BUS-001 Demonstrate the decision chain',
    operationalRequirement: 'ODD violation reduces assistance and is explained and audited',
    systemRequirement: 'SAFE-104, ODD-101',
    useCase: 'UC-08 Operate under GNSS/sensor degradation',
    hazardOrConstraint: 'HAZ-NAV-02 Reliance on degraded position data',
    component: 'safety-engine/oddEngine.ts',
    testScenario: 'GNSS / SENSOR DEGRADATION',
    verificationEvidence: 'Unit test: packages/simulator/src/simulation/engine.scenarios.test.ts ("GNSS / SENSOR DEGRADATION scenario — ODD violation") · No e2e coverage yet',
    verificationStatus: 'partial',
  },
  {
    businessObjective: 'BUS-001 Demonstrate the decision chain',
    operationalRequirement: 'Loss of shore connectivity degrades gracefully without disabling onboard support',
    systemRequirement: 'SIM-002, HMI-204',
    useCase: 'UC-07 Operate through a ship-shore communication loss',
    hazardOrConstraint: 'HAZ-OPS-03 Over-reliance on shore-dependent capability',
    component: 'simulation/engine.ts (fallback_transition), features/operations/*',
    testScenario: 'SHIP-SHORE COMMUNICATION LOSS',
    verificationEvidence: 'e2e: packages/app/e2e/acceptance-journey.spec.ts ("shore-dependent capability falls back while onboard assistance continues, then recovers") · Unit test: packages/simulator/src/simulation/engine.scenarios.test.ts',
    verificationStatus: 'verified',
  },
  {
    businessObjective: 'BUS-002 Reduce workload, preserve authority',
    operationalRequirement: 'A voyage speed recommendation only takes effect after explicit authorisation (L3)',
    systemRequirement: 'ENERGY-001–002',
    useCase: 'UC-09 Optimise voyage speed and energy',
    hazardOrConstraint: 'HAZ-OPS-04 Unintended speed change without human authorisation',
    component: 'store/simulationStore.ts (acceptVoyageRecommendation)',
    testScenario: 'EXCESSIVE FUEL CONSUMPTION',
    verificationEvidence: 'e2e: packages/app/e2e/acceptance-journey.spec.ts ("sense → detect → correlate → recommend → safety validate → human accepts → audit") · Unit test: packages/app/src/store/simulationStore.test.ts',
    verificationStatus: 'verified',
  },
  {
    businessObjective: 'BUS-001 Demonstrate the decision chain',
    operationalRequirement: 'A BLOCKED recommendation is never presented as executable',
    systemRequirement: 'SAFE-001, SAFE-003',
    useCase: 'UC-11 Respond to a safety event',
    hazardOrConstraint: 'HAZ-SAF-01 Automatic execution of a high-risk action',
    component: 'safety-engine/validate.ts',
    testScenario: 'SAFETY EVENT (severe risk, no authority)',
    verificationEvidence: 'Unit test: packages/safety-engine/src/validate.test.ts (BLOCKED reachability and gating) · Unit test: packages/app/src/store/simulationStore.test.ts (a BLOCKED recommendation cannot be accepted or modified) · No e2e coverage yet',
    verificationStatus: 'partial',
  },
  {
    businessObjective: 'BUS-002 Reduce workload, preserve authority',
    operationalRequirement: 'Rejecting a recommendation is a first-class, fully audited outcome',
    systemRequirement: 'HMI-002',
    useCase: 'UC-03 Detect and respond to main engine degradation',
    hazardOrConstraint: 'HAZ-OPS-05 Silent disregard of a safety-relevant recommendation',
    component: 'features/decision/*, store/simulationStore.ts',
    testScenario: 'ENGINE DEGRADATION (human rejects)',
    verificationEvidence: 'e2e: packages/app/e2e/acceptance-journey.spec.ts ("a rejected recommendation is recorded distinctly from acceptance") · Unit test: packages/app/src/store/simulationStore.test.ts',
    verificationStatus: 'verified',
  },
  {
    businessObjective: 'BUS-003 Engineering narrative',
    operationalRequirement: 'A shore-support request is traceable from raising to closure without removing onboard authority',
    systemRequirement: 'SHORE-001–003',
    useCase: 'UC-12 Request shore support',
    hazardOrConstraint: 'HAZ-OPS-06 Ambiguity over who holds decision authority',
    component: 'features/shore/*, store/simulationStore.ts',
    testScenario: 'Any scenario → Request Shore Support',
    verificationEvidence: 'e2e: packages/app/e2e/acceptance-journey.spec.ts ("requesting shore support opens a traceable case in the Shore Operations Centre") · Unit test: packages/app/src/store/simulationStore.test.ts',
    verificationStatus: 'verified',
  },
  {
    businessObjective: 'BUS-004 Independent, self-contained',
    operationalRequirement: 'Connected services fall back to Offline Demonstration Mode and this is shown honestly',
    systemRequirement: 'CYBER-001–002, POC-101',
    useCase: 'UC-14 Ask the Operations Copilot',
    hazardOrConstraint: 'HAZ-DAT-01 Synthetic data mistaken for live data',
    component: 'services/adapters/*, services/pocMode.ts',
    testScenario: 'Connected mode with unreachable backend (default for the public static demo)',
    verificationEvidence: 'Manual review only: POC Data Mode banner shows SIMULATED with reason. Not covered by an automated test.',
    verificationStatus: 'not_verified',
  },
  {
    businessObjective: 'BUS-007 Console display floor',
    operationalRequirement: 'The operations console requires a desktop-class display and shows an explicit notice below it, rather than a broken or misleading layout; the landing page stays fully responsive',
    systemRequirement: 'HMI-401',
    useCase: 'n/a',
    hazardOrConstraint: 'n/a (presentation/UX requirement, not a safety hazard)',
    component: 'layouts/AppShell.tsx, components/layout/SmallScreenNotice.tsx, hooks/useMinViewportWidth.ts',
    testScenario: 'n/a',
    verificationEvidence: 'e2e: packages/app/e2e/small-screen-gate.spec.ts (gate below 900px, landing page intact at 375px with no horizontal scroll, console intact at 1440px, live resize toggles without reload)',
    verificationStatus: 'verified',
  },
]
